/**
 * Extra words the command search finds a command by, in both languages whatever
 * the interface language is - someone who knows "fillet" from another program
 * types it into the German interface too. The keys are the ids of the toolbar
 * buttons (data-layerling-tool) and of the other commands in the palette.
 * Spelling does not matter: the search folds case and umlauts (see commandSearch).
 */
export const COMMAND_KEYWORDS: Readonly<Record<string, readonly string[]>> = {
  copy: ["copy", "kopie", "kopieren"],
  paste: ["paste", "einfuegen", "einfügen"],
  duplicate: ["duplicate", "clone", "doppeln", "verdoppeln", "vervielfaeltigen"],
  delete: ["delete", "remove", "loeschen", "löschen", "entfernen", "weg"],
  history: ["history", "look back", "earlier state", "previous version", "timeline", "verlauf", "zurueckschauen", "zurückschauen", "frueherer stand", "früherer stand", "version", "stand"],
  undo: ["undo", "back", "rueckgaengig", "zurueck", "zurück"],
  redo: ["redo", "wiederholen", "wiederherstellen", "vor"],
  outliner: ["outliner", "object list", "objektliste", "liste", "ebenen", "layers"],
  "toggle-hidden": ["hide", "show", "visible", "ausblenden", "einblenden", "verstecken", "sichtbar"],
  "show-hidden": ["show all", "unhide", "alles zeigen", "alles einblenden", "versteckte"],
  notes: ["notes", "points", "notizen", "punkte", "bezugspunkte"],
  overhangs: ["overhang", "ueberhang", "überhang", "ueberhaenge", "überhänge", "support", "stuetze"],
  group: ["group", "union", "merge", "combine", "gruppieren", "verbinden", "vereinen", "verschmelzen", "aussparung", "hole"],
  bundle: ["bundle", "buendel", "bündel", "buendeln", "bündeln", "ohne verrechnung"],
  ungroup: ["ungroup", "split group", "trennen", "aufloesen", "auflösen", "gruppe aufheben"],
  intersect: ["intersect", "intersection", "schnittmenge", "verschneiden", "gemeinsam"],
  align: ["align", "ausrichten", "buendig", "bündig", "mitte", "center"],
  mirror: ["mirror", "flip", "spiegeln", "spiegelung"],
  pivot: ["pivot", "rotation point", "drehpunkt", "drehen", "rotate"],
  scalePercent: ["scale", "percent", "resize", "bigger", "smaller", "skalieren", "prozent", "vergrößern", "vergroessern", "verkleinern", "größe"],
  array: ["array", "pattern", "repeat", "muster", "reihe", "kreis", "wiederholen", "vervielfachen"],
  split: ["split", "cut", "slice", "teilen", "schneiden", "trennen", "saegen", "sägen", "ebene"],
  snap: ["snap", "grid", "raster", "einrasten", "gitter"],
  chamfer: ["chamfer", "bevel", "fase", "abschraegen", "abschrägen", "kante"],
  fillet: ["fillet", "round", "radius", "verrunden", "abrunden", "runden", "kante"],
  simplify: ["simplify", "decimate", "reduce", "fewer triangles", "optimize", "vereinfachen", "reduzieren", "dezimieren", "weniger dreiecke", "netz", "mesh", "optimieren"],
  hollow: ["hollow", "shell", "aushoehlen", "aushöhlen", "wand", "wandstaerke", "wandstärke", "hohl"],
  drop: ["drop", "lower", "absenken", "auf arbeitsebene", "boden", "ground"],
  layFlat: ["lay flat", "flat", "face down", "auf flaeche legen", "auf fläche legen", "flach", "drucken"],
  center: ["center", "centre", "mitte", "zentrieren", "mittig"],
  note: ["note", "annotation", "point", "reference", "notiz", "anmerkung", "bezugspunkt"],
  import: ["import", "open", "load", "stl", "3mf", "obj", "step", "svg", "oeffnen", "öffnen", "laden"],
  export: ["export", "save", "download", "print", "stl", "3mf", "step", "speichern", "drucken", "lyl"],
  settings: ["settings", "options", "units", "grid", "einstellungen", "optionen", "einheit", "mm", "zoll"],
  guide: ["guide", "help", "manual", "tutorial", "anleitung", "hilfe", "kurzanleitung"],
  shortcuts: ["shortcuts", "keys", "keyboard", "tastenkuerzel", "tastenkürzel", "tastatur", "hotkeys"],
  "mode-geometry": ["3d", "editor", "geometry", "bodies", "koerper", "körper"],
  "mode-sketch": ["sketch", "draw", "2d", "skizze", "zeichnen"],
  "sketch-line": ["line", "polyline", "linie", "gerade"],
  "sketch-bezier": ["bezier", "curve", "kurve", "bogen"],
  "sketch-smooth": ["smooth", "freehand", "freihand", "glatt"],
  "sketch-select": ["select", "move", "auswaehlen", "auswählen", "bewegen"],
  "sketch-image": ["image", "picture", "template", "trace", "bild", "vorlage", "foto"],
  "sketch-refine": ["refine", "points", "punkte", "verfeinern", "nachbearbeiten"],
  "sketch-fillet": ["fillet", "round corner", "ecke", "verrunden", "abrunden"],
  "sketch-chamfer": ["chamfer", "bevel corner", "ecke", "fase"],
  "sketch-erase": ["erase", "delete", "radiergummi", "radieren", "loeschen", "löschen"],
  "sketch-finish": ["finish", "done", "extrude", "fertig", "abschliessen", "abschließen", "fertigstellen"],
  "sketch-cancel": ["cancel", "abort", "abbrechen", "verwerfen"],
  "sketch-extrude": ["extrude", "pull", "push", "extrudieren", "ziehen", "hochziehen", "aufziehen"],
  "sketch-revolve": ["revolve", "lathe", "rotate", "drehkoerper", "drehkörper", "rotieren"],
  "sketch-edit": ["edit sketch", "skizze bearbeiten", "nachbearbeiten"],
};

/** The words of a shape, beyond its name: what people call it elsewhere. */
export const SHAPE_KEYWORDS: Readonly<Record<string, readonly string[]>> = {
  box: ["cube", "block", "quader", "wuerfel", "würfel", "rechteck"],
  roundedBox: ["rounded cube", "abgerundet", "rounded box", "rundquader"],
  cylinder: ["tube", "pipe", "rod", "zylinder", "rohr", "stab", "walze"],
  sphere: ["ball", "kugel"],
  cone: ["kegel", "spitze"],
  text: ["font", "letters", "schrift", "buchstaben", "beschriftung"],
  nameTag: ["name tag", "key ring", "keychain", "multicolour", "multicolor", "layers", "namensschild", "schlüsselanhänger", "schluesselanhaenger", "mehrfarbig", "schichten"],
  gear: ["cog", "zahnrad", "zahnraeder", "zahnräder"],
  thread: ["screw", "bolt", "nut", "gewinde", "schraube", "mutter"],
  hinge: ["scharnier", "gelenk"],
  spring: ["coil", "feder", "spirale"],
  tube: ["pipe", "hollow cylinder", "rohr", "huelse", "hülse"],
  loft: ["loft", "transition", "adapter", "reducer", "funnel", "duct", "uebergang", "übergang", "trichter", "reduzierstueck", "reduzierstück", "eckig auf rund", "square to round"],
  torus: ["ring", "donut", "o-ring", "oring"],
  wedge: ["ramp", "keil", "rampe", "schraege", "schräge", "triangle", "right triangle", "dreieck", "rechtwinklig"],
  polygon: ["triangle", "roof", "hexagon", "dreieck", "dach", "sechskant", "vieleck", "mehrkant"],
  "round-roof": ["roof", "dach", "arch"],
  pyramid: ["pyramide", "triangle", "dreieck"],
  slot: ["capsule", "kapsel", "langloch", "oblong"],
  "half-sphere": ["dome", "halbkugel", "kuppel"],
  star: ["stern"],
  heart: ["herz"],
  ruler: ["lineal", "measure", "messen"],
};
